name: OCaml CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up OCaml
      uses: ocaml/setup-ocaml@v3.4.5
      with:
        ocaml-compiler: 5.3.0
        dune-cache: true

    - name: Install dependencies
      run: opam install . --deps-only --with-test

    # This will help with future debugging
    - name: Show installed packages
      run: opam list

    - name: Check formatting
      uses: ocaml/setup-ocaml/lint-fmt@v3.4.5

    - name: Check opam
      uses: ocaml/setup-ocaml/lint-opam@v3.4.5

    - name: Build
      run: opam exec -- dune build

    # Plug me in when tests pass
    # - name: Run tests
    #   run: opam exec -- dune runtest